name: Deploy React Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/my-app/**"
      - ".github/workflows/deploy-frontend.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: job-decision-copilot-engine-frontend
  CLOUDFRONT_DISTRIBUTION_ID: E3DC2E3NHLRJVB
  VITE_BASE_URL: "https://ptxwcjkfshtqu3c22yhxqe7y240ggxus.lambda-url.ap-south-1.on.aws/api"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/my-app

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::790954697390:role/GitHubDeploymentRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload frontend to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/ --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"